import Link from "next/link";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} flex h-screen`}>
				<nav className="flex flex-col grow basis-0 gap-2 p-4 bg-slate-400">
					<Link href={"/"}>anime gril pics</Link>
					<Link href={"/shite"}>elsewhere idk</Link>
				</nav>
				<main className="flex grow-4 basis-0 overflow-y-scroll">
					{children}
				</main>
			</body>
		</html>
	);
}
