import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./components/NavBar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} flex h-screen`}>
				<NavBar />
				<main className="flex flex-col grow-4 basis-0 p-4 items-center overflow-y-scroll bg-neutral-900">
					{children}
				</main>
			</body>
		</html>
	);
}
